---
title: "Séries Temporais"
author: "Thiago Tavares Lopes Lucas de Bona Sartor"
date: "`r format(Sys.time(), '%d %B %Y')`"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
   - \usepackage{float}
   - \usepackage{multirow}
   - \usepackage{tabularx}
geometry: left=2.5cm, right=2.5cm, top=2cm, bottom=2cm
output:
  bookdown::pdf_document2:
    fig.align: 'center'
editor_options:
  chunk_output_type: console
  markdown: 
    wrap: sentence
---
```{r setup, include=FALSE}
options(encoding = "UTF-8")
options(OutDec = ",")
options(scipen = 999, digits =5)
``` 

```{r, include=FALSE}
# BIBLIOTECAS

suppressMessages(library(forecast))
suppressMessages(library(tseries))
suppressMessages(library(lubridate))
suppressMessages(library(tidyverse))
suppressMessages(library(readr))
suppressMessages(library(ggpubr))
suppressMessages(library(ggplot2))


source("functions.R")
```



```{r, include=FALSE}

#DADOS

dados<- read_csv("dados/Gold Price (2013-2023).csv")

dados <- dados |> 
  mutate(Date = as.Date(Date, format = "%m/%d/%Y"))

media_mensal <- dados |> 
  mutate(Month = floor_date(Date, "month")) |> 
  group_by(Month) |> 
  summarise(Average_Price = mean(Price, na.rm = TRUE))
#View(media_mensal)


data_serie<-ts(media_mensal$Average_Price, frequency=12, start=c(2013,1))


```




# Introdução 

Nesta seção são apresentados os dados referentes a análise da série temporal de precificação mensal do ouro, entre os anos de 2013 e 2023. O banco de dados pode ser encontrado no link XXXXXXX. 


```{r, echo=FALSE, fig.align='center',label="fig1"}
# Gráficos

plot(data_serie, ylab = "Preço Mensal" ,main = "Precificação mensal do Ouro - 2013 a 2023")

```


```{r, echo=FALSE, label="fig2", fig.width=10, fig.height=8, fig.align='center'}
par(mfrow = c(2, 2)) 
acf_plot<-acf(data_serie, main= "Função de Autocorrelação")
pacf_plot<-pacf(data_serie, main = "Função de Autocorrelação Parcial")

```

Resultados de tendência, raiz unitária e sazonalidade


```{r, include=FALSE}

# verificar - Sazonalidade, raiz unitaria e tendencia

tend_determ(data_serie)

raiz_unit(data_serie)

sazonalidade(data_serie)

# resultado - 
```




```{r, include=FALSE}

modelo_ets <- ets(data_serie, model = "MAN", damped = TRUE)

summary(modelo_ets)

Box.test(modelo_ets$residuals,lag=10)

#modelo_ets$residuals

#checkresiduals(modelo_ets)
```

```{r, echo=FALSE}
checkresiduals(modelo_ets, test = F)
```

```{r, echo=FALSE}

#tsdisplay(modelo_ets$residuals, main = "Modelo MAN - Resíduos")



```


```{r, echo=FALSE, message=FALSE}

ggqqplot(modelo_ets$residuals)+
  ggtitle("Resíduos Modelo MAN") +
  theme(plot.title = element_text(hjust = 0.5)) 

```




```{r, include=FALSE}
# diferenciação

# data_serie_diff<-diff(data_serie,differences = 1)
# plot(data_serie_diff)
# acf(data_serie_diff)
# adf.test(data_serie_diff, alternative = "stationary")
# 
# tend_determ(data_serie_diff)
# 
# raiz_unit(data_serie_diff)
# 
# sazonalidade(data_serie_diff)
# 
# plot(data_serie_diff)

```



```{r, include=FALSE}
arima_model<-auto.arima(data_serie)

summary(arima_model)

checkresiduals(arima_model)

ggqqplot(arima_model$residuals)+ggtitle("Res?duos Modelo SES")


```



